### ISSUE TITLE
Error msg lately

### ISSUE THREAD

**Issue by aresstokrat** [sm1ck/snapshotvoter#11]
2 последних воута начало выдавать такую ошибку, хотя голосует вполне успешно,
 => ошибка "client_error": duplicate message в каждом воуте (не рандом)

а потом в какой то момент падает насмерть

[0] Задержка 12с..
[0] express\node_modules\@ethersproject\logger\lib\index.js:238
[0]         var error = new Error(message);
[0]                     ^
[0]
[0] Error: invalid hexlify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.7.0)
[0]     at Logger.makeError (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\logger\lib\index.js:238:21)
[0]     at Logger.throwError (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\logger\lib\index.js:247:20)
[0]     at Logger.throwArgumentError (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\logger\lib\index.js:250:21)
[0]     at hexlify (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\bytes\lib\index.js:200:19)
[0]     at new SigningKey (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\signing-key\lib\index.js:20:82)
[0]     at new Wallet (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\wallet\lib\index.js:120:36)
[0]     at wsVote (file:///D:/scripts/snapshotvoter-web/express/vote/Vote.js:482:23) {
[0]   reason: 'invalid hexlify value',
[0]   code: 'INVALID_ARGUMENT',
[0]   argument: 'value',
[0]   value: ''
[0] }
[0]

**Comment by sm1ck** [comment]
Нужно в конфиге отключить подписку, если это консольный

**Comment by aresstokrat** [comment]
неа, не консольный. Хочу кстати консольный, как его поставить? отдельный репо или прям текущий работает норм?
