### ISSUE TITLE
keys.json

### ISSUE THREAD

**Issue by rocketport** [sm1ck/snapshotvoter#3]
После установки и конфигурирования keys.json запускается, но на моменте голосвания сваливается в ошибку

0] /home/snapshotvoter/express/node_modules/@ethersproject/logger/lib/index.js:238
[0]         var error = new Error(message);
[0]                     ^
[0] 
[0] Error: invalid hexlify value (argument="value", value="приватный_ключ_1", code=INVALID_ARGUMENT, version=bytes/5.7.0)
[0]     at Logger.makeError (/home/snapshotvoter/express/node_modules/@ethersproject/logger/lib/index.js:238:21)
[0]     at Logger.throwError (/home/snapshotvoter/express/node_modules/@ethersproject/logger/lib/index.js:247:20)
[0]     at Logger.throwArgumentError (/home/snapshotvoter/express/node_modules/@ethersproject/logger/lib/index.js:250:21)
[0]     at hexlify (/home/snapshotvoter/express/node_modules/@ethersproject/bytes/lib/index.js:200:19)
[0]     at new SigningKey (/home/snapshotvoter/express/node_modules/@ethersproject/signing-key/lib/index.js:20:82)
[0]     at new Wallet (/home/snapshotvoter/express/node_modules/@ethersproject/wallet/lib/index.js:120:36)
[0]     at wsVote (file:///home/snapshotvoter/express/vote/Vote.js:449:23)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[0]   reason: 'invalid hexlify value',
[0]   code: 'INVALID_ARGUMENT',
[0]   argument: 'value',
[0]   value: 'приватный_ключ_1'
[0] }
[0] 
[0] Node.js v20.2.0
[0] [nodemon] app crashed - waiting for file changes before starting...
^C[0] npm run start --prefix express exited with code SIGINT

При этом в value подставляется приватный_ключ_1 - хотя дефолтный файл потерт и туда вставлены приватники. Откуда оно берет фразу "приватный_ключ_1" если cat keys.json - приватные ключи в корне каталога?

**Comment by sm1ck** [comment]
сейчас ключи лежат в папке express/vote и оттуда же берутся
в корень пока не переносил
