### ISSUE TITLE
not working - bc of VPS?

### ISSUE THREAD

**Issue by aresstokrat** [sm1ck/snapshotvoter#7]
I think its not working bc i use VPS with panel on it. How to config on different port? 

 npm start

> express@1.0.0 start
> nodemon App.js

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node App.js`
(node:2609011) [DEP0151] DeprecationWarning: Package /root/snapshotvoter/express/node_modules/shared/ has a "main" field set to "types/types", excluding the full filename and extension to the resolved file at "types/types.js", imported from /root/snapshotvoter/express/vote/ws.js.
 Automatic extension resolution of the "main" field is deprecated for ES modules.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2609011) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(node:2609011) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1868:16)
    at listenInCluster (node:net:1916:12)
    at Server.listen (node:net:2004:7)
    at wsApp.listen (/root/snapshotvoter/express/node_modules/@wll8/express-ws/dist/src/index.js:71:39)
    at file:///root/snapshotvoter/express/App.js:61:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1895:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 80
}

Node.js v20.4.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by aresstokrat** [comment]
i tryed to add port 90 in the App.js, and its worked !
But at the ip:port application i get this msg every 2-3 sec which deletes every field on the page :((( what to do ?
![image](https://github.com/sm1ck/snapshotvoter/assets/22521162/ac5d822d-4555-4a31-adf6-2c3b878d50bd)

**Comment by aresstokrat** [comment]
i tryed on the local PC, its worked with 2 addresses then crashed:


-----------------
 голос засчитан
[0] Задержка 1с..
[0] D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\logger\lib\index.js:238
[0]         var error = new Error(message);
[0]                     ^
[0]
[0] Error: invalid hexlify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.7.0)
[0]     at Logger.makeError (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\logger\lib\index.js:238:21)
[0]     at Logger.throwError (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\logger\lib\index.js:247:20)
[0]     at Logger.throwArgumentError (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\logger\lib\index.js:250:21)
[0]     at hexlify (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\bytes\lib\index.js:200:19)
[0]     at new SigningKey (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\signing-key\lib\index.js:20:82)
[0]     at new Wallet (D:\scripts\snapshotvoter-web\express\node_modules\@ethersproject\wallet\lib\index.js:120:36)
[0]     at wsVote (file:///D:/scripts/snapshotvoter-web/express/vote/Vote.js:475:23) {
[0]   reason: 'invalid hexlify value',
[0]   code: 'INVALID_ARGUMENT',
[0]   argument: 'value',
[0]   value: ''
[0] }
[0]
[0] Node.js v18.16.1
[0] [nodemon] app crashed - waiting for file changes before starting...
----------------

**Comment by sm1ck** [comment]
I think it's a key issue
